# Generated by Django 3.1.1 on 2020-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matricnum', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('coursecode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=50)),
                ('student', models.ManyToManyField(to='planner.Student')),
            ],
        ),
    ]
