# Generated by Django 3.1.2 on 2020-10-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses_cleared',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
